### ISSUE TITLE
Level Triggers

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#11]
As a developer, I can add different trigger zones to levels that execute different behaviors.
- [ ] Death trigger zone
- [ ] Respawn points triggers
- [ ] Boss fight trigger zone 
- [ ] End level trigger zone
  - [ ] takes the player to the next level
- [ ] Game Over trigger (on death)

**Comment by ClaudiaLapalme** [comment]
Broke down this issue in #63 #64 #65
