### ISSUE TITLE
Random collision with ground tiles

### ISSUE THREAD

**Issue by Wmbat** [WillTarte/EMU#22]
When walking on a straight surface of tiles, the player character sometimes collides with a random tile and cannot move unless it jumps over it

Potential Fix: https://gamedev.stackexchange.com/questions/168600/player-gets-stuck-on-edges-between-tilemapcollider2d-tiles

**Comment by WillTarte** [comment]
This was probably fixed by switching from BoxCollider2D to EdgeCollider2D in the Player's gameobject (#17 )

**Comment by ClaudiaLapalme** [comment]
I haven't had an issue with this since the collider was changed. Is there still a bug?
