### ISSUE TITLE
[STRETCH] Pause Functionality

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#3]
As a player, I can pause the game when inside a level.
- [ ] Pressing some key pauses the game play. (does not break the level)
- [ ] A Pause Screen shows up, where the level is still visible in the background.
- [ ] There is a "Save Game" button that saves the game (See #2 ). [STRETCH]
- [ ] There is a "Main Menu" button that takes you back to the main menu (See #1 ).
- [ ] Can change game options
- [ ] Summary of character stats & inventory [STRETCH]

**Comment by ClaudiaLapalme** [comment]
Closing the stretch as we are reducing the scope of the project (we can always re-open it later if need be)
