### ISSUE TITLE
Bug: rendering layers are not working in the right order

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#32]
The way the game currently is, we have multiple tilemaps for the environment (i.e. 1 for ladders, 1 for the ground, 1 for platforms, etc...) and we also render independent game objects (enemies, weapons, player).

The issue I've noticed is that weapons + bullets sometimes should appear in front of a tile, but appear behind. See supporting screenshot.
![fa91ec8a850a7a5512f7809fe1ab283d](https://user-images.githubusercontent.com/38739890/98167257-c4d35f00-1eb6-11eb-8f74-87c9dff8ef86.png)

**Comment by ClaudiaLapalme** [comment]
Fixed in #67
