### ISSUE TITLE
HUD doesn't show the selected weapon when picking them up

### ISSUE THREAD

**Issue by Aleoris** [WillTarte/EMU#40]

**Comment by WillTarte** [comment]
This might be getting fixed by #43

**Comment by ClaudiaLapalme** [comment]
I think I saw them as selection in the weapon refinement branch

**Comment by ClaudiaLapalme** [comment]
I confirm: This is not a bug. There is a little box around the primary weapon when i pick up a weapon and then i can see when i switch between both
