### ISSUE TITLE
Bug: Falling too fast can cause the player to get stuck inside the ground on landing

### ISSUE THREAD

**Issue by tedgag** [WillTarte/EMU#59]
Self-explanatory and pretty low priority. In normal gameplay there are no situation where this can happen, unless you glitch out.
![100482269-d201f900-30c4-11eb-8667-2ea22b4a0ff3](https://user-images.githubusercontent.com/36055308/100484411-530fbf00-30ca-11eb-8715-7040848ce9e4.png)

**Comment by WillTarte** [comment]
This really only happens if you fall from too high, or move the player through the editor to spawn inside tiles

**Comment by ClaudiaLapalme** [comment]
Now that the player can't climb walls, this is basically impossible + it's out of our control (unity physics), so I'm going to close this issue.
