### ISSUE TITLE
Art & Sprites

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#8]
- [x] Game Logo (Main Menu)
- [x] Main Menu background
- [ ] Level backgrounds
- [ ] Environment
  - [ ] Grass & dirt sprites
  - [ ] Rock sprites
  - [ ] Wood sprites (container and platforms)
  - [ ] Metal sprites (containers and platforms)
  - [ ] Explosive barrel sprites
  - [ ] Different weapon sprites
- [ ] Character sprites (enough for animations)
- [ ] Enemy sprites (different types, enough for basic animations)

**Comment by WillTarte** [comment]
For the player spritesheets:
Different spritesheets with player by itself, player with different weapons

**Comment by ClaudiaLapalme** [comment]
What's left to do:

Player (PRIORITY):
- [ ] rolling
- [ ] climbing
- [ ] falling
- [ ] shotgun character
- [ ] knife character
   - [ ] attack animation (move knife)

Emu (PRIORITY):
- [ ] kamikaze emu
- [ ] boss 1
   - [ ] Melee
   - [ ] Looks like a boss ass bitch
- [ ] boss 2
   - [ ] laser eyes
   - [ ] cyborg like

Interactables (NOT A PRIORITY):
- [ ] chest
   - [ ] open sprite
   - [ ] closed sprite
- [ ] Grenade
- [ ] health pickup (optional last minute shit)
- [ ] ammo pickup (optional last minute shit)
- [ ] explosive barrels
- [ ] metal ladder
- [ ] metal spikes
- [ ] metal platforms
- [ ] backgrounds

City interactables inspo:
![image](https://user-images.githubusercontent.com/32103530/99881727-6bbf3700-2be9-11eb-9c99-a51fb6ab8b75.png)

Outback background inspo:
![image](https://user-images.githubusercontent.com/32103530/99881774-c193df00-2be9-11eb-89c6-3447ff1cbe5a.png)

City background inspo:
![image](https://user-images.githubusercontent.com/32103530/99881786-d53f4580-2be9-11eb-9d78-e5f3e0adce12.png)
![image](https://user-images.githubusercontent.com/32103530/99881815-f011ba00-2be9-11eb-8cdd-dbdf25458271.png)
